version: "3"

# Account #0
x-deployer_pk: &deployer_pk
  DEPLOYER_PRIVATE_KEY: '0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80'

services:
  # deploys account abstraction contracts and serves contract addresses
  aa_deployer:
    depends_on:
      - l1
      - l2
    build:
      context: ..
      dockerfile: ./ops/docker/Dockerfile.bundler
      target: aa_deployer
    image: bobanetwork/aa_deployer:latest
    environment:
      L1_NODE_WEB3_URL: http://l1:8545
      L2_NODE_WEB3_URL: http://l2:8545
      L1_CROSS_DOMAIN_MESSENGER_ADDRESS: ${L1_CROSS_DOMAIN_MESSENGER_ADDRESS}
      L1_STANDARD_BRIDGE_ADDRESS: ${L1_STANDARD_BRIDGE_ADDRESS}
      # DO NOT use in production
      << : *deployer_pk
      RETRIES: 200
      # skip compilation when run in docker-compose, since the contracts
      # were already compiled in the builder step
      NO_COMPILE: 1
    volumes:
      - "${PWD}/../.devnet:/opt/boba/packages/boba/account-abstraction/dist/dumps"

  bundler:
    depends_on:
      - l1
      - l2
      - aa_deployer
    build:
      context: ..
      dockerfile: ./ops/docker/Dockerfile.bundler
      target: bundler
    image: bobanetwork/bundler:latest
    deploy:
      replicas: 1
    ports: [ '3000:3000' ]
    restart: on-failure
    environment:
      MIN_BALANCE: 0
      MNEMONIC_OR_PK: "0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80"
      L1_NODE_WEB3_URL: http://l1:8545
      L2_NODE_WEB3_URL: http://l2:8545
      BENEFICIARY: "0xcd3b766ccdd6ae721141f452c550ca635964ce71"
      ADDRESS_MANAGER_ADDRESS: ${ADDRESS_MANAGER_ADDRESS}
      MAX_BUNDLE_GAS: 5000000
      #should be set to false in prod!
      UNSAFE: 'true'
    mem_limit: 300M
    logging:
      driver: "json-file"
      options:
        max-size: 10m
        max-file: "10"

networks:
  default:
    name: bedrock-devnet
