version: '3.4'

services:
  l2:
    image: bobanetwork/erigon:${VERSION:-latest}
    environment:
      - CHAIN_NAME=optimism-goerli
    ports:
      - "9545:8545"
      - "8551:8551"
    volumes:
      - ./jwt-secret.txt:/config/jwt-secret.txt
      - DATA_DIR:/db
  op-node:
    depends_on:
      - l2
    image: bobanetwork/op-node:${VERSION:-latest}
    command: >
      op-node
      --l1=${ETH1_HTTP:-https://ethereum-goerli.publicnode.com}
      --l2=http://l2:8551
      --l2.jwt-secret=/config/jwt-secret.txt
      --network=goerli
      --rpc.addr=0.0.0.0
      --rpc.port=8547
      --l1.trustrpc=true
      --p2p.disable=true
    ports:
      - "8547:8547"
    volumes:
      - ./jwt-secret.txt:/config/jwt-secret.txt
    restart: always
