version: '3.4'

services:
  boba-regenerate:
    image: bobanetwork/boba-chain-ops
    build:
      context: ..
      dockerfile: ./boba-chain-ops/Dockerfile
    command: boba-regenerate
    environment:
      L2_PRIVATE_ENDPOINT: http://erigon:8551
      L2_PUBLIC_ENDPOINT: http://erigon:9545
      L2_LEGACY_ENDPOINT: ${HISTORICAL_RPC-}
      JWT_SECRET_PATH: /jwt/jwt_secret.txt
    # volumes:
    #   - /:/jwt

  boba-crawler:
    image: bobanetwork/boba-chain-ops
    build:
      context: ..
      dockerfile: ./boba-chain-ops/Dockerfile
    command: boba-crawler
    environment:
      RPC_URL: ${HISTORICAL_RPC-}
      OUTPUT_PATH: '/addr/eth-addresses.json'
    restart: always
    # volumes:
    #   - /:/addr

  erigon:
    image: bobanetwork/erigon:migration
    entrypoint:
      - /bin/sh
      - -c
      - "erigon --datadir=/data --private.api.addr=localhost:9090 --http.addr=0.0.0.0 --http.port=9545 --http.corsdomain=* --http.vhosts=* --authrpc.addr=0.0.0.0 --authrpc.port=8551 --authrpc.vhosts=* --authrpc.jwtsecret=/jwt/jwt_secret.txt --rollup.disabletxpoolgossip=true --chain=${CHAIN-} --http.api=eth,debug,net,engine,erigon,web3 --torrent.port=42068 --rollup.historicalrpc=${HISTORICAL_RPC-} --log.console.verbosity=dbug"
    # volumes:
    #   - /:/data
    #   - /:/jwt
