name: 'Slither Analysis'

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - develop

jobs:
  slither-analyze:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Workaround to prevent slither-action from trying to install JS deps.
      # Without this step, it detects the `package.json``, and since there is no
      # lockfile it defaults `npm install` which fails due to the preinstall
      # script to enforce pnpm. https://github.com/crytic/slither-action/issues/44#issuecomment-1338183656
      - name: Remove package.json
        run: rm packages/contracts-bedrock/package.json

      - name: Install forge
        run: |
          curl -L https://foundry.paradigm.xyz | bash
          source $HOME/.bashrc
          foundryup --version nightly-f625d0fa7c51e65b4bf1e8f7931cd1c6e2e285e9
          echo 'export PATH=$HOME/.foundry/bin:$PATH' >> $BASH_ENV
          source $HOME/.bashrc
          forge --version

      - name: Run Slither
        uses: crytic/slither-action@v0.3.1
        id: slither
        with:
          target: packages/contracts-bedrock
          slither-config: packages/contracts-bedrock/slither.config.json
          fail-on: config
          sarif: results.sarif
          # https://github.com/crytic/slither-action/issues/70#issuecomment-1932948435
          slither-version: dev-triage-db
          slither-args: --triage-database packages/contracts-bedrock/slither.db.json

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: ${{ steps.slither.outputs.sarif }}
